export const ADD_CITY = 'ADD_CITY';
export const ADD_CITY_WEATHER = 'ADD_CITY_WEATHER';
export const DELETE_CITY_WEATHER = 'DELETE_CITY_WEATHER';
export const UPDATE_CITY_WEATHER = 'UPDATE_CITY_WEATHER';
export const DETAIL_CITY_WEATHER = 'DETAIL_CITY_WEATHER';
